### ISSUE TITLE
Akka.js status

### ISSUE THREAD

**Issue by yawnt** [unicredit/akka.js#4]
### AKKA-ACTOR
- [x] `actor/`
- [x] `dispatch/` 
- [x] `event/` 
- [x] `pattern/`
- [x] `routing/`
- [x] `serialization/`
- [x] `util/`
##### TODO
- [x] allow ovewriting of `context` by rewriting IR in `ActorCell.scala`
- [x] remove dependencies from `akka.util.JS*`
- [x] Strategies are mostly missing
- [ ] add support for Workers + routing in ActorPath (partial, will be refactored in `akka-remote`)
- [x] **IMPORTANT** refactor out Java API, maybe with a mixin? We could share this approach with JS (see #6) and provide Java || JS api if we're calling from Scala or Scala.js
- [x] port `typesafe.config.Config` (it's 100% Java, so we can't cross-compile. alternatives? see @mfirry 's suggestion in #5 )
- [x] `sun.misc.Unsafe` (stub implementation vs mixin with traits JS/JVM specific methods?)
- [x] JVM data structures (see #8) 
##### DONE
- [x] move `JSMap` to `TreeMap`
- [x] some `System.getEnv` and `System.getProperty` calls to remove (eg: `ActorSystem.scala`)
- [x] `mailboxTypes` are missing 
- [x] refactor out references to Thread (eg: `Thread.currentThread().interrupt()`)
- [x] implement `event/` (and therefore Logging)
- [x] clean up `setActorFields` in `Actor.scala`
- [x] remove Java imports
- [x] remove Java (`ThreadLocal`, etc) from `ActorCell.scala` and add `lookupAndSetField`
- [x] MalformedUrlException in ActorPath
- [x] Deployer doesn't exist yet
- [x] ActorFor in `ActorRefProvider.scala`
- [x] Implement constructor for Props
- [x] some code depends on DynamicAccess, it needs to be refactored out
- [x] terminationCallbacks in ActorSystem
- [x] fix `override def` in the `EventLoopScheduler` (they override final methods, had to fix by hand)
- [x] `dispatch/AbstractDispatcher.scala` contains some thread-specific logic, refactor it out?
### AKKA-REMOTE

Currently blocked by:
- [x] Lack of a pickling library capable of serializing `Any` ([scala pickling](https://github.com/scala/pickling) should help solve the issue: @phaller @heathermiller )
- [x] Reflection in Scala.js (partial support being discussed [here](https://github.com/scala-js/scala-js/issues/1744))

**Comment by andreaTP** [comment]
a POC with working serialization is already here.
This must now be exploited in a full remote working.
Referring to branch `remote`.

**Comment by shafqatevo** [comment]
Hi @andreaTP, thanks for this excellent work! Is this status up to date as of January 2019? What's the overall status of this project?

**Comment by andreaTP** [comment]
Hey @shafqatevo , thanks for the question and I will be happy to follow up more exaustively in the gitter channel!
Overall the project is in great shape and I'm able to update it to stay in sync with Akka releases with a really low effort ( just released 1.2.5.19 ).
From the initial plans the remoting part is still lacking. But the core is pretty stable and even performant.

Consider that it is integrated in the official Akka documentation and it has been used by several speakers to show Akka capabilities in scalafiddle.

**Comment by shafqatevo** [comment]
Great!

Can you please elaborate what capabilities we would miss as developers until remoting is completed?

Can we currently use web workers as actors?

**Comment by andreaTP** [comment]
@shafqatevo I will be really happy to elaborate around the topic in the gitter channel. Sorry but this is not the right space to chat. Thanks for the interest in the project!!!
