### ISSUE TITLE
Missing data structures

### ISSUE THREAD

**Issue by yawnt** [unicredit/akka.js#8]
Some data structures, which are heavily used in Akka, are currently missing in Akka.js/Scala.js
Most notably:
## TODO
- [x] [`java.util.TreeSet`](http://docs.oracle.com/javase/7/docs/api/java/util/TreeSet.html) 
- [ ] [`java.util.Locale`](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html)
  (https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html)
## DONE
- [x] [`java.util.ConcurrentHashMap`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html) 
- [x] [`java.util.ConcurrentSkipListSet`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentSkipListSet.html)
- [x] [`akka.util.Index`](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/util/Index.scala) (`mutable.HashMap with mutable.MultiMap` is enough for this, we need a generic `Index` to be implemented in JS/JVM code)
- [x] [`java.net.MalformedUrlException`](https://docs.oracle.com/javase/7/docs/api/java/net/MalformedURLException.html)
- [x] [`java.util.AbstractQueue`](https://docs.oracle.com/javase/7/docs/api/java/util/AbstractQueue.html)
- [x] [`java.util.Queue`](https://docs.oracle.com/javase/7/docs/api/java/util/Queue.html)
- [x] [`java.util.LinkedList`](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html)
- [x] [`java.util.concurrent.atomic.AtomicArrayReference`](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicReferenceArray.html)
- [x] [`java.util.concurrent.CopyOnWriteArrayList`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html)
- [x] [`java.util.concurrent.ConcurrentLinkedQueue`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html)
- [x] [`java.util.PriorityQueue`](http://docs.oracle.com/javase/7/docs/api/java/util/PriorityQueue.html)
- [x] [`java.util.Deque`](https://docs.oracle.com/javase/7/docs/api/java/util/Deque.html) 

To allow for 100% Java interoperability we should also implement the DS' supertypes, but it's a pretty big task, maybe we could just do with the basic methods for now?

**Comment by andreaTP** [comment]
ConcurrentHashMap available as soon as:
https://github.com/scala-js/scala-js/pull/1636

**Comment by andreaTP** [comment]
ConcurrentSkipListSet available as soon as:
scala-js/scala-js#1681

**Comment by andreaTP** [comment]
As discussed we will not work on `blocking` stuffs,
so I'm going to remove them from the list ;-)

**Comment by andreaTP** [comment]
please refer to 0.6.4-SNAPSHOT for all the WIP

**Comment by andreaTP** [comment]
Scala js 0.6.4 is going to be published within hours and will include all the data structures needed but Locale.
:satisfied::

**Comment by yawnt** [comment]
:santa: :+1: :100:

**Comment by yawnt** [comment]
added `java.util.TreeSet` to list (needed for `akka.routing`)
@andreaTP

**Comment by andreaTP** [comment]
Next week will work on that.

**Comment by andreaTP** [comment]
Since we have a consistent number of cross compiling sources I think we can close.
